function bootScreen()
n = 0
term.setTextColor(1)
while n <= 1 do
term.setCursorPos(24,18)
write("#")
sleep(0.1)
term.setCursorPos(22,17)
write("#")
sleep(0.1)
term.setCursorPos(21,16)
write("#")
sleep(0.1)
term.setCursorPos(21,15)
write("#")
sleep(0.1)
term.setCursorPos(22,14)
write("#")
sleep(0.1)
term.setCursorPos(24,13)
write("#")
sleep(0.1)
write(" #")
sleep(0.1)
term.setCursorPos(28,14)
write("#")
sleep(0.1)
term.setCursorPos(29,15)
write("#")
sleep(0.1)
term.setCursorPos(29,16)
write("#")
sleep(0.1)
term.setCursorPos(28,17)
write("#")
sleep(0.1)
term.setCursorPos(26,18)
write("#")
sleep(0.1)
term.setCursorPos(24,18)
write(" ")
sleep(0.1)
term.setCursorPos(22,17)
write(" ")
sleep(0.1)
term.setCursorPos(21,16)
write(" ")
sleep(0.1)
term.setCursorPos(21,15)
write(" ")
sleep(0.1)
term.setCursorPos(22,14)
write(" ")
sleep(0.1)
term.setCursorPos(24,13)
write(" ")
sleep(0.1)
write("  ")
sleep(0.1)
term.setCursorPos(28,14)
write(" ")
sleep(0.1)
term.setCursorPos(29,15)
write(" ")
sleep(0.1)
term.setCursorPos(29,16)
write(" ")
sleep(0.1)
term.setCursorPos(28,17)
write(" ")
sleep(0.1)
term.setCursorPos(26,18)
write(" ")
sleep(0.1)
n = n + 1
end
end

function optionSelect()
term.clear()
term.setCursorPos(1,1)
print("Welcome to the installation guide for reactOS")
print("Please select a option")
print("---------------------------------------------")
print("1. Setup Reactor Computer")
print("2. Setup Monitor Computer")
input = read
if input == 1 then
term.clear()
term.setCursorPos(1,1)
term.setTextSize(2)
print("Before you install your Reactor Computer...")
term.setTextSize(1)
print("1. Make sure you have a REGULAR COMPUTER.")
print("2. Place you computer so the back of the computer is touching the Computer Port of the reactor.")
print("3. Place a WIRELESS MODEM on the top of your Computer"
print("Once this is completed type 'c' to continue")
input2 = read
if input2 == c then
shell.run("disk/reactorSetup")
else
print("Please read the instructions...")
sleep(3)
optionSelect()
end
elseif input == 2 then
term.clear()
term.setCursorPos(1,1)
term.setTextSize(2)
print("Before you install your Monitoring System...")
term.setTextSize(1)
print("1. Make sure you have a ADVANCED COMPUTER")
print("2. Make sure you have 14 ADVANCED MONITORS")
print("3. Place TWO ADVANCED MONITORS below your ADVANCED COMPUTER")
print("4. Create a 3 Tall, 4 Wide Panel of 12 ADVANCED MONITORS")
print("5. Place a WIRELESS MODEM on the top of your ADVANCED COMPUTER")
print("Once this is completed type 'c' to continue")
input3 = read
if input3 == c then
shell.run("disk/monitorSetup")
else
print("Please read the instructions...")
sleep(3)
optionSelect()
end
else
optionSelect()
end
end

bootScreen()
optionSelect()
