function bootScreen()

n = 0
term.setTextColor(1)
while n <= 3 do
term.setCursorPos(24,18)
write("#")
sleep(0.1)
term.setCursorPos(22,17)
write("#")
sleep(0.1)
term.setCursorPos(21,16)
write("#")
sleep(0.1)
term.setCursorPos(21,15)
write("#")
sleep(0.1)
term.setCursorPos(22,14)
write("#")
sleep(0.1)
term.setCursorPos(24,13)
write("#")
sleep(0.1)
write(" #")
sleep(0.1)
term.setCursorPos(28,14)
write("#")
sleep(0.1)
term.setCursorPos(29,15)
write("#")
sleep(0.1)
term.setCursorPos(29,16)
write("#")
sleep(0.1)
term.setCursorPos(28,17)
write("#")
sleep(0.1)
term.setCursorPos(26,18)
write("#")
sleep(0.1)
term.setCursorPos(24,18)
write(" ")
sleep(0.1)
term.setCursorPos(22,17)
write(" ")
sleep(0.1)
term.setCursorPos(21,16)
write(" ")
sleep(0.1)
term.setCursorPos(21,15)
write(" ")
sleep(0.1)
term.setCursorPos(22,14)
write(" ")
sleep(0.1)
term.setCursorPos(24,13)
write(" ")
sleep(0.1)
write("  ")
sleep(0.1)
term.setCursorPos(28,14)
write(" ")
sleep(0.1)
term.setCursorPos(29,15)
write(" ")
sleep(0.1)
term.setCursorPos(29,16)
write(" ")
sleep(0.1)
term.setCursorPos(28,17)
write(" ")
sleep(0.1)
term.setCursorPos(26,18)
write(" ")
sleep(0.1)
n = n + 1
end

function installOS()
shell.run("copy /disk/reactor /startup")
end

term.clear()
term.setCursorPos(1,1)
print("Installing reactOS Reactor. Version 1.0")
print("Copyright © 2014 Timothy Roe, Jr.")
bootScreen()
installOS()
term.clear()
term.setCursorPos(1,1)
print("reactOS has been installed on this system.")
write("Your Computer will reboot.")
write(".")
write(".")
write(".")
write(".")
shell.run("reboot")
